name: BookieImpl test

on:
  push:
    branches:
      - '*'  # O la branch su cui vuoi triggerare i test

jobs:
  test-specific-file:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del codice sorgente
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configurazione di Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Puoi cambiare la distribuzione se necessario
          java-version: '18'       # Cambia con la versione di Java che usi nel progetto

      # Step 3: Cache delle dipendenze Maven (facoltativo, per ottimizzare il tempo di build)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4: Compilazione del progetto
      - name: Build project
        run: mvn clean install -pl bookkeeper-server -am

      # Step 5: Eseguire i test sul file specifico
      - name: Run specific test
        run: mvn test -Dtest=BookieImplTest#testGetListOfEntriesOfLedger
